Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: true
  Exclude:
    - ./ui.rb

Metrics/MethodLength:
  Enabled: true
  Exclude:
    - ./ui.rb
